#!/usr/bin/env python3
"""
Emit VSA forward instances bound to fastvideo::VariableBlockMask.

CK's own codegen cannot produce these: it picks a mask type from traits.mask_type,
which only describes window geometry. The tile shapes below mirror the ones CK
generates for the VSA receipt (see build/codegen/*.cpp) so the masked and
unmasked instances differ in nothing but the mask.

One file per instance keeps them compiling in parallel; a single translation unit
would serialise eight VSA kernels and dominate build time.

Usage:
    python3 gen_vbs_instances.py <output_dir>
"""
import sys
from pathlib import Path

# Only skpad=false instances are emitted. VSA pads the KV sequence out to whole
# 64-token cubes, so seqlen_k is always a multiple of kN0 and the tail inside the
# last cube is what the mask handles. The wrapper enforces this.
SKPAD = "false"

# (head_dim, block_m) -> (block tile sequence, warp repeat along M)
SHAPES = {
    (64, 128): ("128, 64, 32, 64, 32, 64", 4),
    (64, 64): ("64, 64, 32, 64, 32, 64", 2),
    (128, 128): ("128, 64, 64, 128, 32, 128", 4),
    (128, 64): ("64, 64, 32, 128, 32, 128", 2),
}

DTYPES = {"bf16": "FmhaSparseFwdBf16", "fp16": "FmhaSparseFwdFp16"}

INSTANCE = """// SPDX-License-Identifier: MIT
// auto generated by gen_vbs_instances.py -- do not edit

#include "ck_tile/ops/fmha/block/variants.hpp"
#include "fmha_fwd_trek.hpp"
#include "pipeline/block_fmha_pipeline_qr_ks_vs_async_vsa.hpp"
#include "kernel/fmha_fwd_vsa_kernel.hpp"

#include "vsa_variable_block_mask.hpp"
#include "vsa_vbs_fwd.hpp"

namespace {{

using dtype_ = {ck_dtype};

using block_tile_ = ck_tile::sequence<{tile}>;

using shape_ = ck_tile::TileFmhaShape<block_tile_,
                                      ck_tile::sequence<{rm}, 1, 1>,
                                      ck_tile::sequence<32, 32, 16>,
                                      ck_tile::sequence<{rm}, 1, 1>,
                                      ck_tile::sequence<32, 32, 16>,
                                      true>;

// spad, skpad, dpad, dvpad, logits_soft_cap, bias, bias_grad, store_lse,
// dropout, quant_scale, occupancy, skip_min_seqlen_q, sink
using tile_traits_ = ck_tile::TileFmhaTraits<true,
                                             {skpad},
                                             true,
                                             true,
                                             false,
                                             ck_tile::BlockAttentionBiasEnum::NO_BIAS,
                                             false,
                                             true,
                                             false,
                                             ck_tile::BlockAttentionQuantScaleEnum::NO_SCALE,
                                             -1,
                                             false,
                                             false>;

using variant_ = ck_tile::ComposedAttention<0, CK_TILE_FMHA_FWD_FAST_EXP2>;

using mask_ = fastvideo::VariableBlockMask<64>;

using problem_ = ck_tile::BlockFmhaPipelineProblem<
    typename FmhaSparseFwdTypeConfig<dtype_>::QDataType,
    typename FmhaSparseFwdTypeConfig<dtype_>::KDataType,
    typename FmhaSparseFwdTypeConfig<dtype_>::VDataType,
    typename FmhaSparseFwdTypeConfig<dtype_>::SaccDataType,
    typename FmhaSparseFwdTypeConfig<dtype_>::SMPLComputeDataType,
    typename FmhaSparseFwdTypeConfig<dtype_>::BiasDataType,
    typename FmhaSparseFwdTypeConfig<dtype_>::RandValOutputDataType,
    typename FmhaSparseFwdTypeConfig<dtype_>::LSEDataType,
    typename FmhaSparseFwdTypeConfig<dtype_>::PDataType,
    typename FmhaSparseFwdTypeConfig<dtype_>::OaccDataType,
    typename FmhaSparseFwdTypeConfig<dtype_>::ODataType,
    shape_,
    false,
    variant_,
    mask_,
    false,
    tile_traits_>;

using pipeline_ = ck_tile::BlockFmhaPipelineQRKSVSAsyncVSA<problem_>;

using epilogue_ = ck_tile::Default2DEpilogue<
    ck_tile::Default2DEpilogueProblem<typename FmhaSparseFwdTypeConfig<dtype_>::OaccDataType,
                                      typename FmhaSparseFwdTypeConfig<dtype_>::ODataType,
                                      true,
                                      true>>;

using kernel_ = ck_tile::FmhaFwdVSAKernel<pipeline_, epilogue_>;

}} // namespace

namespace fastvideo {{

float {fn}(const vsa_vbs_fwd_args& a, const ck_tile::stream_config& s)
{{
    auto [kargs, grids]                    = vbs_create_kargs_and_grids<kernel_>(a);
    const dim3 blocks                      = kernel_::BlockSize();
    constexpr ck_tile::index_t kBlockPerCu = kernel_::kBlockPerCu;
    return ck_tile::launch_kernel(
        s, ck_tile::make_kernel<kBlockPerCu>(kernel_{{}}, grids, blocks, 0, kargs));
}}

}} // namespace fastvideo
"""

API = """// SPDX-License-Identifier: MIT
// auto generated by gen_vbs_instances.py -- do not edit

#include "vsa_vbs_fwd.hpp"

namespace fastvideo {{

{decls}

float fmha_vsa_vbs_fwd(fmha_vsa_fwd_traits t,
                       const vsa_vbs_fwd_args& a,
                       const ck_tile::stream_config& s)
{{
    // block_m is a Q-tile hint; 0 means "no preference" and takes the 128 tile,
    // matching the CK-generated dispatcher.
    const bool want_m128 = (a.block_m == 128 || a.block_m == 0);
    if(a.hdim_q % 8 != 0 || a.hdim_v % 8 != 0 || !t.is_v_rowmajor)
        return -1;
    if(a.seqlen_k == 0 || a.seqlen_k % 64 != 0)
        return -1;

{dispatch}
    return -1;
}}

}} // namespace fastvideo
"""

DISPATCH_ARM = """    if(t.data_type == "{dt}" && t.hdim_q <= {hd} && t.hdim_v <= {hd} && {cond})
        return {fn}(a, s);
"""


def fn_name(hd: int, dt: str, bm: int) -> str:
    return f"fmha_vsa_vbs_fwd_d{hd}_{dt}_m{bm}"


def main(out_dir: str) -> None:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    decls, dispatch = [], []
    # Ascending head dim so the `hdim <= N` arms are tried narrowest first.
    for hd in sorted({h for h, _ in SHAPES}):
        for dt, ck_dtype in DTYPES.items():
            for bm in (128, 64):
                tile, rm = SHAPES[(hd, bm)]
                fn = fn_name(hd, dt, bm)
                (out / f"{fn}.cpp").write_text(
                    INSTANCE.format(ck_dtype=ck_dtype, tile=tile, rm=rm, skpad=SKPAD, fn=fn)
                )
                decls.append(
                    f"float {fn}(const vsa_vbs_fwd_args& a, const ck_tile::stream_config& s);"
                )
                dispatch.append(
                    DISPATCH_ARM.format(
                        dt=dt,
                        hd=hd,
                        cond="want_m128" if bm == 128 else "a.block_m == 64",
                        fn=fn,
                    )
                )

    (out / "fmha_vsa_vbs_fwd_api.cpp").write_text(
        API.format(decls="\n".join(decls), dispatch="".join(dispatch))
    )
    print(f"Generated {len(decls)} variable-block-mask instances in {out}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise SystemExit("Usage: gen_vbs_instances.py <output_dir>")
    main(sys.argv[1])
